### ISSUE TITLE
[Unity] Secondary texture not exported

### ISSUE THREAD

**Issue by davidzwa** [BabylonJS/BabylonToolkit#1]
Unity's secondary albedo texture is not used, but can very easily be used to tile the texture.
Unity merges the secondary texture, but I see no advantage for that in BabylonJS.

We would be better off by taking the secondary albedo texture as primary once given and by using the uScale and vScale on the material in the scene to map the tiling X and Y from Unity. This way the designer does not have to attach a Mesh Component, EditorScriptComponent to the component and dive into the owner.material and adjust it just for 1 simple property.

**Comment by MackeyK24** [comment]
New custom material system in upcomping toolkit allow any custom material with custom properties and custom shader code. Also supports shader chunks. Then you can do what evver you want with your Unity .shader (Custom Properties) and your babylon material and your babylon .fx files.

Coming soon :)
