### ISSUE TITLE
I buld the script babylon.manager.js and use it ,but it can't work.What should I do?

### ISSUE THREAD

**Issue by shenxiyou** [BabylonJS/BabylonToolkit#10]

**Comment by sebavan** [comment]
Ping @MackeyK24 :-)

**Comment by MackeyK24** [comment]
I dunno what that means... Have to show example or screen shot or something

**Comment by shenxiyou** [comment]
sorry, I mean I want to change to code and rebuild the babylon.manager.js base [Manager](https://github.com/BabylonJS/UnityExporter/tree/master/Manager).but it can't work

**Comment by MackeyK24** [comment]
Manager from the classic edition old and only supported **INSIDE** the Classic Edition Unity Exporter.

The one in the REPO... is the new GLTF based Scene Manager and not really ready. It is the current Scene Manager on the Playground and is only really code based right now (You do everything through code and not the unity exporter... Remember the Unity Exporter is just that... An Exporter)

But if you really wanna mess with the Scene Manager project...

Download Project...
in root project folder, type: 
**npm install** to setup project libs

and

**gulp** to compile project

Again... This new Manager does not work in the Classic Edition Unity Exporter... Its a new GLTF Based Scene Manager i am working on. Hope that doesn't confuse things too much

**Comment by MackeyK24** [comment]
You can now download the **Classic Edition** scene manager: https://github.com/BabylonJS/UnityExporter/tree/master/Classic/Manager

1... Download project
2... npm install
3... gulp

**Comment by shenxiyou** [comment]
Thank you very much.
