### ISSUE TITLE
Assets/Babylon/Sources/Editors/LightScale.cs(17,37): error CS0122: `UnityEditor.LightEditor' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by ChampRay** [BabylonJS/BabylonToolkit#12]
Everytime I import, this is the error I get.

Assets/Babylon/Sources/Editors/LightScale.cs(17,37): error CS0122: `UnityEditor.LightEditor' is inaccessible due to its protection level

Assets/Babylon/Sources/Editors/LightScale.cs(19,30): error CS0115: `UnityEditor.LightScaleEditor.OnInspectorGUI()' is marked as an override but no suitable method found to override

It doesn't load the toolbar at the top of the unity editor.

I am using Windows 10, Unity 5.63p2 Personal(64 bit)

**Comment by ChampRay** [comment]
pinging @MackeyK24

**Comment by MackeyK24** [comment]
What version of Unity are you using?

**Comment by ChampRay** [comment]
As written in the original post

> I am using Windows 10, Unity 5.63p2 Personal(64 bit)

Are you referring to a different type of version?

**Comment by MackeyK24** [comment]
I missed that... But update your unity to latest version... Works with Unity 2018 & 2019 Builds

**Comment by MackeyK24** [comment]
I take it updating from unity 5 worked?

**Comment by ChampRay** [comment]
Yes, thank you very much.

**Comment by MackeyK24** [comment]
No Problem :)
