### ISSUE TITLE
Looped animation glitches when used in a blend tree

### ISSUE THREAD

**Issue by dyvoid** [BabylonJS/BabylonToolkit#14]
This applies to animations being used in a Unity Animator Controller.

Please see attached examples:
[glitch_example_files.zip](https://github.com/BabylonJS/UnityExporter/files/3729260/glitch_example_files.zip)

walk_normal.mp4: 
Animation works as expected when used in a normal animation state.

walk_glitch.mp4: 
The animation glitches on loop when used in a simple blend tree. The blend tree in question here uses 4 animations, all of which glitch in the same way, at the end of their respective loops (they have varrying lengths).

animation_state.jpg:
Shows the settings of the Animation State component.

animator.jpg:
The setup of the Animator Controller. Just a simple blend tree node as default starting point.

blend_tree.jpg
The setup of the blend tree.

**Comment by MackeyK24** [comment]
Attached files not available... please re upload example files

**Comment by dyvoid** [comment]
Are you sure? They work for me. Here they are again just to make sure:
[glitch_example_files.zip](https://github.com/BabylonJS/UnityExporter/files/3733173/glitch_example_files.zip)

**Comment by MackeyK24** [comment]
Blend Trees no longer supported in legacy edition of toolkit
