### ISSUE TITLE
FileNotFound Exceptions while Exporting

### ISSUE THREAD

**Issue by kvinsu** [BabylonJS/BabylonToolkit#15]
Once clicking Build and Preview, I am getting three FileNotFound Exceptions for .hdr-Files. The project itself is working, but I am concerned that these Exceptions might pose a problem in the future.
![Console](https://user-images.githubusercontent.com/28533473/69795907-4e6dad80-11cd-11ea-8abb-174fa2d1c599.jpeg)

**Comment by sebavan** [comment]
ping @MackeyK24.

You should have an answer shortly but there might be a bit of delay with Thanksgiving :-)

**Comment by MackeyK24** [comment]
Dunno bout this... where is that hdr coming from???

Can you package up the scene and send to me so i can try on build on my end ???

**Comment by NightmareNinja** [comment]
Mail is sent! :)

**Comment by kvinsu** [comment]
Mail is sent @MackeyK24 !

**Comment by MackeyK24** [comment]
Maybe its something with the version of Unity you are using... What the version ???

I just open your 3DModelViewer.unitypackage (Which includes the babylon toolkit folder, so i didnt have to add anything to your project)

It Build just Fine.... No funny .hdrm missing file error:

![Screen Shot 2019-11-29 at 1 28 23 AM](https://user-images.githubusercontent.com/5013415/69866350-e6a87880-1247-11ea-91b1-903eee7c6fda.png)


And it show your spinning cube just fine:


![Screen Shot 2019-11-29 at 1 28 39 AM](https://user-images.githubusercontent.com/5013415/69866364-f2943a80-1247-11ea-98e8-db8a6fceee95.png)


So try updating your Unity... Also... If you are not using Unity Hub to maintain your Unity Versions.... You really should :)

**Comment by kvinsu** [comment]
I'm currently using the current LTS Unity one (still 2018), does that make a difference?

**Comment by MackeyK24** [comment]
Try the latest 2019 version

**Comment by MackeyK24** [comment]
Dunno... Looks like some kind of TEMP file issue on your system.

The ExportReflectionsRaw function DOES make a temp HDR file for the environment... But that is pretty standard .NET File IO.

Please use Latest Unity 2019 which is now .NET 4.0 based and does not have any local temp file issues.
