### ISSUE TITLE
Duplicate Ionic.zip.dll makes this incompatible with Bolt install. 

### ISSUE THREAD

**Issue by sacb0y** [BabylonJS/BabylonToolkit#16]
I get an error with the Ionic.zip.dll file since bolt uses a version of that too. Seems deleting one or the other creates issues and i can't seem to make a working build of the most basic scene.

Perhaps using bolt at all isn't viable but I figured i'd let you guys know...

**Comment by sebavan** [comment]
Ping @MackeyK24.

You should have an answer shortly but there might be a bit of delay with Thanksgiving :-)

**Comment by MackeyK24** [comment]
I will probably remove Ionic.zip as a dependency since we no longer download zip packages 📦

**Comment by MackeyK24** [comment]
Removed Ionic Zip dependency
