### ISSUE TITLE
Thank you for the project! 

### ISSUE THREAD

**Issue by JohMun** [BabylonJS/BabylonToolkit#19]

**Comment by JohMun** [comment]
I can create a scene like this in the browser
![image](https://user-images.githubusercontent.com/20238661/90830668-63353700-e342-11ea-91ec-39dd52cb27c2.png)

**Comment by fenos** [comment]
I'll add myself to the topic by giving back at least a huge THANK YOU, for this project.
Keep up the amazing work!
