### ISSUE TITLE
Example project (space shooter, rollaball)

### ISSUE THREAD

**Issue by davidzwa** [BabylonJS/BabylonToolkit#2]
[U3D Toolkit] Is there any sample project to work with?
For example the source code of the live game would be 1000% better than the current docs.
https://www.babylontoolkit.com/projects/spaceshooter/

**Comment by MackeyK24** [comment]
I will have to make a new roll a ball and space shooter demo project using the new toolkit. When I can get to it :)

**Comment by davidzwa** [comment]
@MackeyK24 see https://github.com/davidzwa/BabylonUnityLearnings for that. Based on an older version of your exporter.
