### ISSUE TITLE
Where is **Component in UnityExporter?

### ISSUE THREAD

**Issue by freemavis** [BabylonJS/BabylonToolkit#23]
![image](https://user-images.githubusercontent.com/25631659/105791935-bda58400-5fc1-11eb-9ddc-b99cc7a43252.png)
I can not find **Component type in /Assets/[Babylon]/Template/Typings folder.
Unity version: 2020.1.17
UnityExporter Version:5.0.0 A66

**Comment by MackeyK24** [comment]
That looks like a script from toolkit.

For the new toolkit you must create a new script ... btw... there is now only one base class call d BABYLON.ScriptComponent
