### ISSUE TITLE
Project not building on Unity 2020.3.6

### ISSUE THREAD

**Issue by LuchoTurtle** [BabylonJS/BabylonToolkit#25]
Hey there,  Mackey! 
Thank you very much for contributing to this toolkit, I wager all the Babylon community highly appreciates it! 

I'm trying to use the toolkit to create a small, low-poly styled map and I'm wishing to import it to Babylon.js running on the browser. I was trying to use Unity as the editor, and seeing your tool is kind of the _de facto_ exporter from Unity to Babylon, I was trying to give it a whirl.

I followed the steps on [this thread](https://forum.babylonjs.com/t/require-extension-cvtools-babylon-mesh-is-not-available/17592/9) that but I can't seem to get it working with the latest Unity 2020.3.6 - it always says that the project failed to build.

### What I changed on a fresh project
I followed the steps of the video, which included:
- In **Project Settings -> Graphics**, unticked "Reflection Probes Blending" on all Tiers.
- In **Project Settings -> Players**, changed "Color Space" to Linear.
- In **Project Settings -> Players**, unticked "Auto Graphics API for Windows"
- In **Project Settings -> Players**, put "OpenGLCore" on top on all platforms (which lead to the editor being restarted).
- Created a lightning object, and disabled "Progressive Updates", set "Lightning Mode" to Subtractive and changed "Directional Mode" to Non-Directional.

I'm a bit lost on what I can do to make this work. Any pointers?

Thank you!

**Comment by MackeyK24** [comment]
I made a demo for light baking, but i go thru the whole initial project setup.

Take a look at the video in this thread

https://forum.babylonjs.com/t/require-extension-cvtools-babylon-mesh-is-not-available/17592/9

**Comment by LuchoTurtle** [comment]
Hey there!
Yeah, I've linked the demo you sent on my initial comment hehe. Either way, with your new version, it seems to be working. Although I've added terrain and a few trees and parsing the scene content seems to run indefinitely 🤔

**Comment by LuchoTurtle** [comment]
Okay, it seems that the problem is related to the Terrain component itself. I can't seem to get a preview working with Terrains, even ensuring that the Bake Light option is toggled on in all components 😦

**Comment by MackeyK24** [comment]
Let me try with Unity 2020.3.6f1

**Comment by LuchoTurtle** [comment]
Cheers! If you want to, I can give you my project! It's a clean project with the aforementioned settings changed :)

**Comment by MackeyK24** [comment]
So i just tested with 2020.3.6f1 my default Candy Land scene to test terrain and splatmap shader for  all the patterns in the terrain.

Unity Shot

![Screen Shot 2021-05-05 at 11 08 41 AM](https://user-images.githubusercontent.com/5013415/117209804-931e5080-ad92-11eb-952f-0a48beefb258.png)


Babylon Render

![Screen Shot 2021-05-05 at 11 08 17 AM](https://user-images.githubusercontent.com/5013415/117209841-a03b3f80-ad92-11eb-8082-ea5e803ecf46.png)


Looks great

**Comment by MackeyK24** [comment]
Send me your scene, i try take a look at when i can

**Comment by LuchoTurtle** [comment]
@MackeyK24 Thanks a lot! Here's a [downloadable link](https://www.mediafire.com/file/1dy65ll7vveeink/porter2.zip/file). It only has terrain and a cube. It builds just fine but the parsing of the scene content goes on forever when I check on the browser.

Thanks a lot for the help and sorry for being such a bother! :/

**Comment by MackeyK24** [comment]
Please move this issue to the forums so others with the same problem can see the solution. 

If you check the console, there is an out of memory error with ammo.js.

![Screen Shot 2021-05-06 at 8 53 02 AM](https://user-images.githubusercontent.com/5013415/117350820-b60b3c00-ae48-11eb-8996-0ad2860513a4.png)

You terrain is really tall... 600 you might wanna lower that in general.

You can control which AMMO STACK you would like to include in your project. It default to a 128MB ammo build.
I raise that to 256MB for Ammo Stack

![Screen Shot 2021-05-06 at 8 56 03 AM](https://user-images.githubusercontent.com/5013415/117351236-2c0fa300-ae49-11eb-8ec9-2b6d4fba807c.png)

And you final scene

![Screen Shot 2021-05-06 at 8 57 06 AM](https://user-images.githubusercontent.com/5013415/117351258-35990b00-ae49-11eb-8805-5948af8ee11e.png)

**Comment by LuchoTurtle** [comment]
Thanks a lot! I'll post it on the forums for everyone to see! Sorry for bothering!
