### ISSUE TITLE
Missing Some System Components

### ISSUE THREAD

**Issue by fenos** [BabylonJS/BabylonToolkit#26]
Hello there!
Thanks a lot for this amazing plugin.

I was scanning through the documentation and there are quite a bit handy scripts that come with the plugin.

I was specifically interested in the [CharacterComponent ](https://doc.babylonjs.com/extensions/Unity/01_ScriptComponents#character-controller) but it doesn't appear in the dropdown as well as few other mentioned in the doc. Any idea?

![image](https://user-images.githubusercontent.com/4754064/118281388-0deb1800-b4c5-11eb-8cd3-93506474c9ee.png)

**Comment by MackeyK24** [comment]
It now uses the native Unity Character Controller component... And the BABYLON class you use is **BABYLON.CharacterController**

```
const controller = this.getComponent("BABYLON.CharacterController");
if (controller != null) {
     controller.move(velocity);
}
```

**Comment by fenos** [comment]
@MackeyK24  Ahh thanks a lot for that!

I've played around with it and it's very nice!
However, i've noticed something very weird (probably i'm doing something wrong) maybe you can help.


As soon as I add the CharacterComponent to a 3D capsule when the game load I see the capsule being under my map level.

I'm not sure why at this stage, but it could either be that the map load after the character is spawned and the gravity is pushing it down. Or I'm not sure what's going on.

Here is what's happening:

![image](https://user-images.githubusercontent.com/4754064/118377398-e9766500-b5c4-11eb-81dc-2de7576253fb.png)

When the game Load:

![image](https://user-images.githubusercontent.com/4754064/118377417-057a0680-b5c5-11eb-9381-4b92b548ef03.png)


Both the capsule and the world have collisions

**Comment by MackeyK24** [comment]
First of all... you have both a capsule collider and a character controller on the game object. You dont need both.
You EITHER use a capsule collider and  normal rigid body physics to move you game object around with setLinearVelocity.

Or

You use the Kinematic Character Controller to move you game object around using the controller.move function.

In either case there is a Center property on the both colliders... you need to use that to offset the the collision fopr the game object... Try putting in 1 in the Y for the center... That should offset the collision mesh... You should be able to see this in the Unity scene before you export

... 

If you still cant get working... send me the scene ill will fix it up and show you whats the what

**Comment by fenos** [comment]
@MackeyK24 I see! that did the trick! Apologies for my newbie question.
Is there a way for me to contact you privately please,
I'd love to ask you a few questions about the toolkit and general best practices

my email is: fabri.feno@gmail.com

i'll be happy to share the scene
