### ISSUE TITLE
Material not rendering

### ISSUE THREAD

**Issue by LuchoTurtle** [BabylonJS/BabylonToolkit#27]
Hey there!
Sorry for disturbing again but I feel stuck trying to preview my simple scene with rather basic material and shaders. I've added a basic terrain and material, like in the picture below.

![image](https://user-images.githubusercontent.com/17494745/118380151-9528b080-b5d7-11eb-961f-23c88b50b7ba.png)

However, when I preview the scene, the material doesn't seem to render...
![image](https://user-images.githubusercontent.com/17494745/118380169-b12c5200-b5d7-11eb-8358-643aa8dc6bae.png)

I'm using a rather simple texture and using a standard shader in Unity. I've tried to use both Unity's and Babylon's standard shader but it doesn't seem to make any difference...

I've tried to look through the documentation regarding shader materials but it doesn't really help. Any thoughts?

Thank you!

**Comment by MackeyK24** [comment]
Is it an actual terrain ?
Can you package up and send me the scene ?

**Comment by LuchoTurtle** [comment]
Yes, it is. It's a simple terrain where I'm using the preview package Terrain Tools (I don't know if that might be the cause of it). I'm using it because I might need it in the future, I'm aware that for the screenshots I sent they're overkill.

Regardless, here's the [project file](https://www.mediafire.com/file/1kwu85d780qqo1p/porter2.zip/file). Sorry for disturbing!

**Comment by MackeyK24** [comment]
First... you have to choose a terrain shader like (Nature/Terrain/Diffuse or Nature/Terrain/Standard)...

Second... I do not support the new Mask Map texture slot. Only Main and Normal Terrain Textures

Third... I do not support the new experimental terrain tools (may or may not work)

**Comment by LuchoTurtle** [comment]
Alright, thanks for the clarification!
