### ISSUE TITLE
how to identity the right version with unity?

### ISSUE THREAD

**Issue by cpzhang** [BabylonJS/BabylonToolkit#28]
hi, first of all ,it's great job !
but how to identity the right version with unity? Unity has many different versions ,like unity5 and unity 2017 and unity2018 ...etc， and this babylonsjs unityexporter also has many unitypackage versions, how to match them?
thanks

**Comment by MackeyK24** [comment]
Babylon Toolkit: Version 5 requires Unity 2020.1 (Or Greater)
