### ISSUE TITLE
[HowTo] Augmented reality feature

### ISSUE THREAD

**Issue by AytoMaximo** [BabylonJS/BabylonToolkit#32]
Hello! I'm not sure about the best place to ask such a question. 

If there any info/documentation about implementing WebAR via Unity? I've found a component called "Universal Camera System" and there you can change main camera type to "Augmented reality". When I run this project on my mobile device I can see camera feed, but the 3D object is not acting like "augmented" one, it moves with the camera.

Honestly, I'm not a web developer guy, I'm experienced only in Unity, so I can't figure it all out by myself :(

**Comment by AytoMaximo** [comment]
Seems like I've manage to fix that wrong behavior, but still curious about some tips and tutorials on WebAR topic :)

**Comment by MackeyK24** [comment]
I am still working things out with WebXR in general in the Universal Camera Controller
