### ISSUE TITLE
No default project file selected ?

### ISSUE THREAD

**Issue by pxim** [BabylonJS/BabylonToolkit#33]
![image](https://user-images.githubusercontent.com/5111701/127270252-fac5a898-e3ce-4330-81bf-87169d8fd035.png)

I've clearly selected the model file

unity 2020.2
unityExporter Babylon Editor Toolkit (Early 2020).unitypackage

![8](https://user-images.githubusercontent.com/5111701/127287538-2f064ce3-8294-4801-b5a3-5a45c4047c18.gif)

**Comment by MackeyK24** [comment]
It look like you dont have the project export folder setup properly. I have outlined the project export folder section.

![Screen Shot 2021-07-28 at 10 27 14 AM](https://user-images.githubusercontent.com/5013415/127391389-fa2fd6ae-83c9-4039-8a59-941490754fe1.png)

**Comment by pxim** [comment]
> It look like you dont have the project export folder setup properly. I have outlined the project export folder section.
> 
> 

![image](https://user-images.githubusercontent.com/5111701/127415017-ced11ddb-026a-4fb7-8b58-6c19364f8a7a.png)


https://github.com/prefrontalcortex/UnityGLTF
This plug-in is less powerful, but at least it can export GLTF normally in unity2020

**Comment by MackeyK24** [comment]
Now it looks like you dont have default light settings

![Screen Shot 2021-07-28 at 6 39 38 PM](https://user-images.githubusercontent.com/5013415/127432904-16a8ed15-a591-4b64-9f02-c61d82bcfdf0.png)

**Comment by MackeyK24** [comment]
Her is a video i made for baking lightmaps. But the beginning part of this video does all the actual project setup...

All the project settings and Light Settings to get started

https://babylontoolkit.com/videos/testlightmaps.mp4

**Comment by pxim** [comment]
> Her is a video i made for baking lightmaps. But the beginning part of this video does all the actual project setup...
> 
> All the project settings and Light Settings to get started
> 
> https://babylontoolkit.com/videos/testlightmaps.mp4

First of all, thank you very much for this detailed video .
But，This looks like a lot of trouble .

Is there an easy to use method，like https://github.com/BabylonJS/Exporters/releases .
This plugin for exporting GLTF is especially useful in Max , and it's easy to get started .

---
unity 2020.2  +  Babylon Editor Toolkit 2019.unitypackage
Can be used normally.
![image](https://user-images.githubusercontent.com/5111701/127465367-79274975-5202-49c7-8dc4-d14968027fc5.png)
![image](https://user-images.githubusercontent.com/5111701/127465773-44159772-c7c4-4c33-bb91-d5531d7618dd.png)

But the exported scene is only in Babylon format .
I want the GLB format .

---
unity 2020.2  +  Babylon Editor Toolkit (Early 2020).unitypackage
unity 2020.2  +  2021/Babylon Editor Toolkit.unitypackage
None of them work properly

---
This is the example
https://drive.google.com/file/d/1AY6DyfkfVoEKOQciKTLlAb00jAPJMIvy/view?usp=sharing

**Comment by MackeyK24** [comment]
My latest toolkits are for creating entire babylon projects right in the unity editor. It focus on using the babylon.mamanger.js extension to make game development in BabylonJS more Unity Like. We use Script components on top of that to add logic.

You can actually turn off all the meta data and set to right handed export... that we produce a PLAIN GLTF (Like UnityGLTF).
But you dont get ANY of the extras i add to the toolkit that the scene manager parses... like lightmaps.

Anyways... the latest versions work as expected. It is what we use daily at my job to create 3D content. Check out what you can make with the toolkit: https://www.vx360events.com/

But you can always just use blender or max or what ever to make your standard gltf content.

You could also try fixing up the UnityGLTF exporter to your liking

My toolkit is for creating content for the babylon.manager.js extension 

Best of luck with whatever you decide to use :)

**Comment by pxim** [comment]
Ok, thank you for advice .

unity 2020.2 + Babylon Editor Toolkit (Early 2020).unitypackage
Now I have added the light map ,
then GLB and scene can export normally .

But the model animation is not brought out .

---

Select the entire scene, then Babylon → Scene Exporter → Project Publishing → Export File Format → GLB → Export Scene . 
![image](https://user-images.githubusercontent.com/5111701/127594111-b70f1497-c295-4b7c-aca2-42ba9cae24c0.png)

I put the exported GLB on this website and found it has animation
https://gltf-viewer.donmccurdy.com/

This method can be used to export animations from Unity

Very good ！

**Comment by MackeyK24** [comment]
As i mention... You can turn **OFF METADATA**, select **RIGHT HANDED** and **PRIMITIVE MESHES** from the options... That will make a regular right handed GLTF without extra unity metadata... Basically a plain old GTLF with PBR materials and it also includes animations

**Comment by pxim** [comment]
> As i mention... You can turn **OFF METADATA**, select **RIGHT HANDED** and **PRIMITIVE MESHES** from the options... That will make a regular right handed GLTF without extra unity metadata... Basically a plain old GTLF with PBR materials and it also includes animations

Yes, as you said, thank you very much .

---

Can add a function configuration `Draco compression`  when exporting GLB .
