### ISSUE TITLE
The metal map effect is not coming out ！

### ISSUE THREAD

**Issue by pxim** [BabylonJS/BabylonToolkit#34]
I put the GLB in the export folder `Export\scenes` into the website preview and found that the effect is different .
![image](https://user-images.githubusercontent.com/5111701/127801251-b0070bf1-ff24-49db-a35f-80d69098adb2.png)
![image](https://user-images.githubusercontent.com/5111701/127801011-8ff9bfcc-b03f-4b49-8945-41dca7bd6096.png)
![image](https://user-images.githubusercontent.com/5111701/127802726-a2b956f5-125c-4b1e-94fb-aff7bcf3adfd.png)

This is the unity project file :
https://drive.google.com/file/d/12_y1NVML-G3gkvxieDPzTFlxsnTH_sQX/view?usp=sharing

This is the glb :
https://drive.google.com/file/d/10lqTL0zCUYqIEpgF9JpCqD00nb6cWzRj/view?usp=sharing

This is the gltf preview website :
https://gltf-viewer.donmccurdy.com/

@MackeyK24 help me , please

**Comment by pxim** [comment]
> I put the GLB in the export folder `Export\scenes` into the website preview and found that the effect is different .
> ![image](https://user-images.githubusercontent.com/5111701/127801251-b0070bf1-ff24-49db-a35f-80d69098adb2.png)
> ![image](https://user-images.githubusercontent.com/5111701/127801011-8ff9bfcc-b03f-4b49-8945-41dca7bd6096.png)
> ![image](https://user-images.githubusercontent.com/5111701/127802726-a2b956f5-125c-4b1e-94fb-aff7bcf3adfd.png)
> 
> This is the unity project file :
> https://drive.google.com/file/d/12_y1NVML-G3gkvxieDPzTFlxsnTH_sQX/view?usp=sharing
> 
> This is the glb :
> https://drive.google.com/file/d/10lqTL0zCUYqIEpgF9JpCqD00nb6cWzRj/view?usp=sharing
> 
> This is the gltf preview website :
> https://gltf-viewer.donmccurdy.com/

**Comment by pxim** [comment]
This may be a problem with my renderer Settings .

https://jsfiddle.net/zpjq8ycb/1/

https://discourse.threejs.org/t/physicallycorrectlights-true-some-materials-became-very-black/28611

**Comment by MackeyK24** [comment]
Dunno, things work pretty good with the PBR Material export in my day to day job. My artist use it every day and sell to clients and everything looks fine

**Comment by pxim** [comment]
No problem with plugins .
This is the problem of my own three code, which has been solved now .
