### ISSUE TITLE
Unity exporter Tag with spaces incorrectly split up

### ISSUE THREAD

**Issue by davidzwa** [BabylonJS/BabylonToolkit#4]
Tags are incorrectly split up when they have a space in Unity.
In Unity it is only 1 tag, so it should stay that way.

![image](https://user-images.githubusercontent.com/6005355/52013461-6c9b4c00-24dd-11e9-931a-ed2c41df501b.png)

**Comment by MackeyK24** [comment]
I cant see how i can fix this for FREE TEXT fields that you can enter tags like "Tag1 Tag2 Tag2"

You wil have to UNDERSCORE your spaced tags like "Tag_1 Tag_2 Tag_3" or i will have to switch the tags to an array (Which might not be a bad ideal anyways) and replace tag value .Replace(" ", "_") or something like that... But this will be in the new version coming soon :)
