### ISSUE TITLE
MissingMethodException: Method not found: UnityEngine.Cubemap UnityEngine.RenderSettings.get_customReflection()

### ISSUE THREAD

**Issue by DarXector** [BabylonJS/BabylonToolkit#40]
Greetings,

I'm using Unity 2021.2.1f1 and Babylon Toolkit: V5.0.0-A48.6X9

When try to Export Scene I get the following issue, and get stuck on Importing assets:

MissingMethodException: Method not found: UnityEngine.Cubemap UnityEngine.RenderSettings.get_customReflection()
CanvasTools.CanvasToolsExporter.OnExportScene (SceneExporterTool exporter, System.String name, UnityEngine.Transform[] rootObjTransforms) (at <e84b440935ef49b3a88454df3b81b693>:0)

**Comment by MackeyK24** [comment]
Unity changed the static property for custom skybox reflection texture (Cubemap DDS)

I made an update [Babylon Toolkit Update](https://github.com/BabylonJS/UnityExporter/tree/master/Redist/2021) (Version 5.0.0-A48.9x9) that uses .net reflection to find the custom reflection texture.
