### ISSUE TITLE
camera not showing skybox

### ISSUE THREAD

**Issue by ersaurabh101** [BabylonJS/BabylonToolkit#43]
unity 2021.2.6f1
unity exporter - 2021

My scene is showing grey background
![image](https://user-images.githubusercontent.com/50316624/149659871-61f4c4b9-02b9-4537-ab3d-494dc4cb4ccf.png)

Where as in unity3d everything is showing fine

![image](https://user-images.githubusercontent.com/50316624/149659890-3c9ada06-4721-4397-96c0-6a4b010b2880.png)

Please guide

**Comment by MackeyK24** [comment]
Show me a snapshot of the the **Lighting** tab that has the environment info on it. And show me the camera setup

**Comment by MackeyK24** [comment]
Is this still an issue ?

**Comment by MackeyK24** [comment]
Closing
