### ISSUE TITLE
A strange pattern on the plane when preview

### ISSUE THREAD

**Issue by tidus2020** [BabylonJS/BabylonToolkit#44]
[https://vkceyugu.cdn.bspapp.com/VKCEYUGU-089368f0-11e8-4a64-b8b7-3cef76e7f67f/2c502a49-debd-4610-9b7a-cc24873cacaa.png](url)

**Comment by MackeyK24** [comment]
Its probably self shadowing.

Either tweak the bias or dont cast a shadow from the plane... Just receive shadows on the plane

**Comment by tidus2020** [comment]
> 

0^0 thanks !
