### ISSUE TITLE
How to get the BABYLON.Scene?

### ISSUE THREAD

**Issue by tidus2020** [BabylonJS/BabylonToolkit#45]
I want use scene.actionManager to manage the keyboard and pointer input.

**Comment by MackeyK24** [comment]
So what is your question ?

**Comment by tidus2020** [comment]
> So what is your question ?

I mean...how to get scene instance in the scriptComponent?

In babylon, i can create the new BABYLON.Scene in the entry "Main.ts", but in UnityExporter, the entry is SceneController and i need to code in the script.

**Comment by MackeyK24** [comment]
the toolkit is scene loader based. So you export a scene in gltf format from the exporter... Then you load that scene... the babylon.manager.js has the gltf extensions required to support all the unity features.

So you dont create new a scene manually... but you load a scene instead for the Unity content

if you want to manually create your scene then you would use SceneLoader.AppendScene or ImportMeshes to load your unity content and have all the unity stuff supported
