### ISSUE TITLE
Source Code // Want to tinker

### ISSUE THREAD

**Issue by ColtraneNadler** [BabylonJS/BabylonToolkit#46]
Hey @MackeyK24 !

Would it be possible to make the source code available? Or send to me directly?
I see it was mostly removed a few years ago in some old commits.

Would like to tinker with instanced meshes with a lightmap attached.

Thanks so much!

**Comment by MackeyK24** [comment]
The newer upcoming pro version of toolkit does not ship source code

**Comment by ColtraneNadler** [comment]
How do we get access to the source code?

**Comment by MackeyK24** [comment]
The newer upcoming pro version of toolkit does not ship source code. The older non GLTF version 4 has source if you need to see how something was being done.
