### ISSUE TITLE
[Unity] export sometimes fails

### ISSUE THREAD

**Issue by davidzwa** [BabylonJS/BabylonToolkit#5]
Sometimes the exporter seems to trigger the preview too soon and the scene is not served:
![image](https://user-images.githubusercontent.com/6005355/51952447-d6154f00-2438-11e9-8777-08ae1dc681ed.png)
Sources:
![image](https://user-images.githubusercontent.com/6005355/51952492-fe04b280-2438-11e9-926a-c05eb2289fb7.png)
And after a reload it works fine, so it seems to me the exporter skips a job (maybe VS is still compiling and the exporter should bug out or wait even?)
![image](https://user-images.githubusercontent.com/6005355/51952503-0eb52880-2439-11e9-9c1e-3a813e09a952.png)

Btw, the RollABall but then newly Babylonized! 💃

**Comment by MackeyK24** [comment]
Dunno ... will have to send me project so I can play with it

**Comment by davidzwa** [comment]
@deltakosh thanks mate. This is better

**Comment by MackeyK24** [comment]
This issue sometimes creeps up if the ASYNC loading that happens in project.js gets out of wack.
This issue is fixed in the upcoming toolkit.

**Comment by davidzwa** [comment]
👍
