### ISSUE TITLE
Not supported on latest Unity 2021 LTS

### ISSUE THREAD

**Issue by SimonDarksideJ** [BabylonJS/BabylonToolkit#52]
Tested importing the UnityExporter latest release ([Babylon Editor Toolkit_5.0.0_A63.unitypackage](https://github.com/BabylonJS/UnityExporter/blob/master/Redist/Alpha/Babylon%20Editor%20Toolkit_5.0.0_A63.unitypackage)) and it was not able to import the asset.

Failures reported:

* Script loading/update error related to CanvasTools.dll -> API has changed and Unity could not update
* CanvasTools.dll has a strong reference to Newtonsoft.Json -> V12.  Min version in Unity 2021 LTS is V13 (no Plugins/json folder found)

To replicate, simply
* Create a new 2021 LTS project
* Import 5.0.0_A63 asset
* See errors

As there is no source for any of the plugins or components, this is not usable on 2021 LTS

**Comment by Christian-Vasilev** [comment]
I can cofirm, tonight I've ran into the same error. Exactly the same steps to reproduce

**Comment by pbsmart** [comment]
![image](https://user-images.githubusercontent.com/34563231/184054664-0df088b0-27ee-4e96-952a-64d43a776eae.png)
Shut down the problem can be solved by this option

**Comment by MackeyK24** [comment]
The new upcoming Pro version will support Unity 2021 and Unity 2022 Editors
