### ISSUE TITLE
Using Tools -> Exporter -> Compile generates errors

### ISSUE THREAD

**Issue by SimonDarksideJ** [BabylonJS/BabylonToolkit#53]
When using the babylon.js exporter, clicking on the "Compile Script" button only generates errors (see below)
![image](https://user-images.githubusercontent.com/1793042/172347328-c3a88496-2a32-4c7b-8401-92bad712eb0f.png)

However, when using "Launch Web Preview", the preview opens as expected.

## Replication instructions

* New Unity 2020 project
* Import latest Asset
* New Scene
* Add cube 
* Configure lightmapping and recommended options
* Open Exporter window with Tools -> Babylon -> Scene Exporter
* Click "Compile Script" (note that no additional scripts have been added to project, it is clean)

The same occurs using the "Build Project" button

(Export Scene does not)

**Comment by MackeyK24** [comment]
Are you sure you script section is pointing to right Node and TSC command line tools
