### ISSUE TITLE
Warnings regarding "incorrect settings" should include a hyperlink to a page describing proper setup

### ISSUE THREAD

**Issue by SimonDarksideJ** [BabylonJS/BabylonToolkit#54]
There seem to be a "multitude" of warnings built in to the exporter which appear in different scenarios:

* Some appear on opening the project (OpenGL instead of DIrect3D, lightmap settings, etc)
* Others only appear on Exporting the scene (Subtractive lighting, non-directional lighting, etc)

I think it would be immensely helpful that instead of just some text about the error, the warnings should also include a hyperlink to a page describing ALL the configuration required to use the exporter correctly.

> Please visit aka.ms/babylonexportersetup for more details on configuring your project.

Oh and a page for how to setup your Unity project correctly with all the required settings, from Lightmap setup to all the various Player / lighting configurations.  I checked https://doc.babylonjs.com/extensions/Unity/Projects and it does not seem to cover all the required/warned settings.

**Comment by MackeyK24** [comment]
I am working on docs for the new Pro version. Its ONLY ME working on this stuff in my spare time.
