### ISSUE TITLE
Where I can find babylon starter content unitypackage?

### ISSUE THREAD

**Issue by yingshixiaohu** [BabylonJS/BabylonToolkit#59]
Hi there, 
I watched the “unity toolkit getting started guide” video at “https://www.babylontoolkit.com/videos/GettingStarted.mp4.  But i can not find the unitypackage refered in guide video ( babylon starter content.unitypackage).  

Anyone know where i can find the package ?

**Comment by MackeyK24** [comment]
Those packages are not ready for the public yet, sorry
