### ISSUE TITLE
Camera doesn't work without starter content package

### ISSUE THREAD

**Issue by alex1998ander** [BabylonJS/BabylonToolkit#62]
As mentioned in [this issue](https://github.com/BabylonJS/UnityExporter/issues/59), the starter content package is not yet available. I'm trying to create a WebXR app for the Quest 2, but I can't seem to get the camera working without the Camera Rig script of the tutorial video. I can export the scene, but when I open it on my Quest 2, I don't see the button to go into VR. Is there some sort of workaround for this? Am I missing something?

**Comment by MackeyK24** [comment]
The core functionality is on babylon.manager.js... Everything else is just script component. I started out creating starter content as a just a way for me to create reusable script components for easy and quick setup. But you can do the same thing... Just a make your own camera script and add the functionality you want there.

Note the new starter content i created (really for jump starting my own projects) for the new toolkit versions are like AS-IS script components ... you can take them and do what you want... Study them as reference for your own scripts or you use them AS-IS or even modify them to do what you want... even the [Pro] classes that will be available to Babylon Toolkit Subscription Developers are MIT/AS-IS... do what you want with. I offer the pre-made scripts are a jump start and to show a way of doing something with the PRO version.

You can always just use the core functionality of babylon.manager.js and write all you own scripts
