### ISSUE TITLE
Need a menu action to export mulitple assets as separate files

### ISSUE THREAD

**Issue by nicolasayotte** [BabylonJS/BabylonToolkit#64]
When your workflow requires all assets to be export to gltf independently (say, for just-in-time loading when you have a large amount of assets), it is extremely tedious to export them all manually. It would be very easy and quick from the plugin to offer a menu item that would say Export Selected as Separate Assets (or whatever) and loop over the selected prefabs.

Thanks

**Comment by nicolasayotte** [comment]
I have gained a lot of time by setting Babylon Tool > Export Selection to a keyboard shortcut (CTRL-ALT-S) and then doing this

```
Ctrl-Alt-s # BJS tool > export selection
Enter      # accept file name
Enter      # to confirm Done
Ctrl-4     # to get back to Hierarchy In the editor
Down Arrow # go to next prefab
```
To export to a specific folder you can change the Project Export Path (temporarily) before doing this.


But this is still tiresome and error prone.

**Comment by MackeyK24** [comment]
Unfortunately I don't support this feature. I added Export Selection to export selected items as prefabs in either GLTF or GLB format. I don't know i have the time to go back into the code exporter and add this functionality

**Comment by MackeyK24** [comment]
Dont know i can do much here, for now
