### ISSUE TITLE
Support WEBP for textures

### ISSUE THREAD

**Issue by nicolasayotte** [BabylonJS/BabylonToolkit#65]
WEBP offers full transparency support (32-bit) and is very space efficient as compared to PNG.

**Comment by nicolasayotte** [comment]
But, I mean, only if you think 80-95% smaller file size matter in web.

![image](https://github.com/BabylonJS/UnityExporter/assets/7725061/54194863-5103-454a-92f2-33343332c143)

**Comment by MackeyK24** [comment]
I dont know how to encode webp textures... is there a C# WEBP encoder I can use from Unity ?

**Comment by nicolasayotte** [comment]
https://developers.google.com/speed/webp/faq#how_do_i_use_libwebp_with_c

Google explains it

**Comment by MackeyK24** [comment]
I am going to look into this... You should contact me via email: MackeyK24@gmail.com

Lets make sure your running the newer builds

**Comment by MackeyK24** [comment]
Yo @nicolasayotte 
Finally Done... Latest Babylon Toolkit: 7.3.2 build support WEBP

![Screenshot 2024-04-24 at 2 44 03 PM](https://github.com/BabylonJS/UnityExporter/assets/5013415/328b749a-4df6-42c3-9c5c-ce4a3dca43df)

**Comment by MackeyK24** [comment]
WEBP works for BULLET AND HAVOK builds

**Comment by nicolasayotte** [comment]
> WEBP works for BULLET AND HAVOK builds
> 

Nice!! Will test and come back to you

**Comment by MackeyK24** [comment]
Shit, I forgot to upload the new builds... So re-download to get the latest
*WEBP* update.

Which I love now, I use the *WEBP* options all the time...

Note: Lightmaps, heightmaps and splatmaps are still exported as lossless
png to main pixel precision

I default color maps to *-q90* and normal maps to *-q10*

**Comment by MackeyK24** [comment]
Yo @nicolasayotte 

Checkout the **built in compression** support for **webp** compressed textures and **gzipped** gltf scene files

https://forum.babylonjs.com/t/compressed-interactive-unity-gltf-content/50105

Here is a demo playground using full compression where its possible. Lightmaps, heightmaps and splatmaps still use lossless png to main the pixel precision needed for **hdr lighting** and **terrain texture blending**

https://playground.babylonjs.com/index.html?UnityToolkit#3T5CUF
