### ISSUE TITLE
Are humanoid avatar animated models and animations possible?

### ISSUE THREAD

**Issue by torchesburn** [BabylonJS/BabylonToolkit#69]
Im talking about the bone remapping and re-targeting of animations that unity3d is capable of, whether that is taken into account on the export?

**Comment by MackeyK24** [comment]
Yes... All Unity animations are re-targted. Both generic and humanoid. Then can also be shared and dynamiclly assign to runtime character avatars like Ready Player Me. but the runtime avatar support requires a Babylon Toolkit Premium developer license
