### ISSUE TITLE
Multiplayer with colyseus not found

### ISSUE THREAD

**Issue by GLukaz** [BabylonJS/BabylonToolkit#70]
I have tried setup a connection to colyseus

let colyseusSDK = new Colyseus.Client("ws://localhost:2567");

but colyseus module is not found on exported and colyseus.js is not included in the runtime

**Comment by MackeyK24** [comment]
My Colyseus based networking solution requires Babylon Toolkit Premium developer license. Then you get the Babylon Toolkit Game Server as well as the updated client script components
