### ISSUE TITLE
Replace .unitypackage with a proper UPM package

### ISSUE THREAD

**Issue by andybak** [BabylonJS/BabylonToolkit#71]
I was a bit surprised to find .unitypackages uploaded directly to the repo. Usually the source goes in the repo and the .unitypackages are uploaded to Releases.

In any case - UPM is the modern way to handle things. Happy to work on a PR if it's likely to be accepted.

**Comment by andybak** [comment]
I've just looked at this a bit more closely - the only Unity code is in a Legacy folder and it's using Siccity's GLTF code. Is this the plan going forward? Unity has "blessed" GLTFast for import and UnityGLTF has recently had a huge update.

Would they be a better starting points?

**Comment by MackeyK24** [comment]
Yo @andybak ... If you can build this from the .unity packages... That would be awesome :)

**Comment by MackeyK24** [comment]
Babylon Toolkit is not published as Unity Package Manager install.

In Unity's Package Manager: Click the "+" button ➔ Add package from git URL....

Community Edition
```
https://github.com/codewrxai/CommunityEdition.git
```

Professional Edition
```
https://github.com/codewrxai/ProfessionalEdition.git
```

**Comment by andybak** [comment]
Just to clarify for others - as I originally misread their comment.

They have forked and repackaged Babylon as a UPM package - which is fantastic.

@MackeyK24 - any idea if this will get merged back in to the official repo? It's a big improvement.

**Comment by MackeyK24** [comment]
The previous version was hard coded to work from the Assets/[Babylon] folder. I dont see they could have gotten it to fully work as a UPM.

But now I natively support UPM


Git Installation
In Unity's Package Manager

Click "+" Button ➔ Add package from git url....

Community Edition

https://github.com/babylontoolkit/communityedition.git
Professional Edition

https://github.com/babylontoolkit/professionaledition.git
Local Installation
In Unity's Package Manager

Click "+" Button ➔ Add package from tarball....

Community Edition

https://github.com/babylontoolkit/communityedition/releases
Professional Edition

https://github.com/babylontoolkit/professionaledition/releases

**Comment by MackeyK24** [comment]
Done
