### ISSUE TITLE
can  I export glb without KHR_materials_pbrSpecularGlossiness ？

### ISSUE THREAD

**Issue by Happy0Ending** [BabylonJS/BabylonToolkit#74]
hello，I export a glb file from unity scene,it can't import in blender.I found that this file has entensionsRequired  KHR_materials_pbrSpecularGlossiness.Can I export a glb model without the KHR_materials_pbrSpecular Glossiness extension?

**Comment by MackeyK24** [comment]
Yes... Dont use Standard Specular (or any Unity shader with specular glossiness workflow).

Stick to the **Standard** shader. That uses the GLTF 2.0 Default Metallic Roughness workflow the specular extension is not needed

**Comment by Happy0Ending** [comment]
I just deleted some mesh, so I can import Blender.Do you have an email? I can send you these two files, they both exceed 25MB.
Also, is there a way to obtain the source code for UnityExporter? I only need the 2022.3. X version. I have some good ideas about lighting baking to web pages, and I have also obtained some model data by restoring GLB to GLTF myself. I want to automate the entire process. In addition, for Draco compression of the model, I developed a desktop application to compress the model, including compressing textures(More precisely, it is cutting the texture to a certain size).

Can you give me some help? Thank you.
