### ISSUE TITLE
Doesn't load into Toolbar on Import

### ISSUE THREAD

**Issue by randomevents** [BabylonJS/BabylonToolkit#9]
First time installer, was really confused about the instructions until I saw the video that had toolbar item for the toolkit,

Windows 10 Enterprise 
Unity 5.6.3p2 (64 bit), upgraded from 5.6.something to see if that was the issue

Console Errors:
- Assets/Babylon/Sources/Editors/LightScale.cs(17,37): error CS0122: `UnityEditor.LightEditor' is inaccessible due to its protection level
- Assets/Babylon/Sources/Editors/LightScale.cs(19,30): error CS0115: `UnityEditor.LightScaleEditor.OnInspectorGUI()' is marked as an override but no suitable method found to override

**Comment by randomevents** [comment]
Same non result on 2019.1.0f2
Different Console Error though:
- error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Files - Programming\Projects\Unity\BabylonJS\Assets\Babylon\Plugins\System.Drawing.dll' and 'C:\Program Files\Unity\Hub\Editor\2019.1.0f2\Editor\Data\NetStandard\compat\2.0.0\shims\netfx\System.Drawing.dll'. Remove one of the duplicate references.

**Comment by randomevents** [comment]
Once, I deleted the System.Drawing.dll from the Asset Folder, the package was recompiled and added to the toolbar

**Comment by ghost** [comment]
Same here.
Deleteting System.Drawing.dll makes the babylon menu appear.

**Comment by MackeyK24** [comment]
I will remove it from next build

**Comment by MackeyK24** [comment]
Removed
